### ISSUE TITLE
fails installation with poetry, AssertionError

### ISSUE THREAD

**Issue by lisphilar** [erdogant/scatterd#2]
Dear @erdogant ,
Thank you very much for creating useful packages!

With Poetry, I tried to install `scatterd` package. However, the following error was raised.

```Bash
$ poetry add scatterd
Using version ^1.1.2 for scatterd

Updating dependencies
Resolving dependencies... (0.4s)

  AssertionError

  at ~/.poetry/lib/poetry/mixology/incompatibility.py:60 in __init__
       56│                     # intersection, they're mutually exclusive, making this incompatibility
       57│                     # irrelevant, since we already know that mutually exclusive version
       58│                     # ranges are incompatible. We should never derive an irrelevant
       59│                     # incompatibility.
    →  60│                     assert by_ref[ref] is not None
       61│                 else:
       62│                     by_ref[ref] = term
       63│ 
       64│             new_terms = []
```

https://github.com/python-poetry/poetry/issues/1985 suggested cyclic dependencies were found in the package installation. The following codes of [scatterd/setup.py](https://github.com/erdogant/scatterd/blob/eac253a7ecf9b39690dd63ba73f66156b362617c/setup.py#L17-L19) may be the cause of this error.

```Python
     install_requires=['matplotlib','numpy','colourmap','seaborn','scatterd'],
     python_requires='>=3',
     name='scatterd',
```

We can replace them with

```Python
     install_requires=['matplotlib','numpy','colourmap','seaborn'], # 'scatterd' deleted
     python_requires='>=3',
     name='scatterd',
```

If acceptable, please review pull request #1. Thank you!
(I'd like to use `scatterd` via your `pca` package in my COVID-19 data analysis project as a dependency.)

**Comment by erdogant** [comment]
Thank you for this fix! I created a new release!
Update to the latest version with:
`pip install -U scatterd.`

**Comment by lisphilar** [comment]
Thank you for the qucik update!
I confirmed we can install scatterd 1.1.3 and pca without errors.
